version: "3"
services:
  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: quarkus
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5400:5432"
      - 
  keycloak:
    image: bitnami/keycloak:latest
    restart: always
    container_name: keycloak
    volumes:
      - "./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json:Z"
    command:
      - start-dev
      - --import-realm
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: quarkus
      DB_PASSWORD: quarkus
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "7777:8080"
    depends_on:
      - postgres-keycloak
